version: "2.0"
services:
    app:
        build: .
        # image: rid9/hibiki-elixir:tag
        ports:
            - "8080:8080"
        links:
            - postgres
        env_file:
            - prod.env
        depends_on:
            - postgres
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=docker
        volumes:
            - postgres:/var/lib/postgresql/data
