version: "2.0"
services:
    hibiki:
        # build: .
        image: rid9/hibiki-elixir:__TAG__
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hibiki.rule=Host(`hibiki.ridho.dev`)"
            - "traefik.http.routers.hibiki.entrypoints=websecure"
            - "traefik.http.routers.hibiki.tls.certresolver=myresolver"
            - "traefik.docker.network=global"
        links:
            - postgres
        env_file:
            - prod.env
        depends_on:
            - postgres
        networks:
            default:
            global:
                aliases:
                    - hibiki
        volumes:
            - ./data:/app/data
        ports:
            - "10000:8080"
    postgres:
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD=docker
        volumes:
            - ./postgres:/var/lib/postgresql/data

networks:
    global:
        external: true
