version: "2.0"
services:
    app:
        # build: .
        image: rid9/hibiki-elixir:1.10.0
        ports:
            - "8080:8080"
        links:
            - postgres
        env_file:
            - prod.env
        depends_on:
            - postgres
        networks:
            default:
            global:
                aliases:
                    - hibiki
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=docker
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            default:

networks:
    global:
        external: true
    default:
